export enum DeviceNames {
  LAYER_FLOAT = 'LAYER_FLOAT',
  TEMP = 'TEMP',
  VOLUME_PERCENT = 'VOLUME_PERCENT',
  TOTAL_VOLUME = 'TOTAL_VOLUME',
  WEIGHT = 'WEIGHT',
  DENSITY = 'DENSITY',
  VOLUME = 'VOLUME',
  LAYER_LIQUID = 'LAYER_LIQUID',
}
