const AUTH = {
  JWT_ACCESS_TOKEN_SECRET: 'secret',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: 14400,
  JWT_REFRESH_TOKEN_SECRET: 'secret',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: 100800,
};

export default Object.freeze(AUTH);
