import { MigrationInterface, QueryRunner } from 'typeorm';

/*eslint-disable*/
export class AddCD1756719260726 implements MigrationInterface {
  name = 'AddCD1756719260726';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "carrier" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "updatedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "deletedAt" datetime, "fullName" varchar NOT NULL, "shortName" varchar, "isEnabled" boolean NOT NULL DEFAULT (1))`,
    );
    await queryRunner.query(
      `CREATE TABLE "dock" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "updatedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "deletedAt" datetime, "fullName" varchar NOT NULL, "shortName" varchar, "isEnabled" boolean NOT NULL DEFAULT (1))`,
    );
    await queryRunner.query(
      `CREATE TABLE "temporary_operation" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "updatedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "deletedAt" datetime, "type" varchar CHECK( "type" IN ('outcome','supply','internal','mixed','return') ) NOT NULL, "status" varchar CHECK( "status" IN ('created','started','progress','interrupted','stopped','finished') ) NOT NULL DEFAULT ('created'), "vehicleState" text, "destination" text, "numberTTN" text, "startedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "finishedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "docVolume" float NOT NULL, "factVolume" float, "factWeight" float, "docWeight" float NOT NULL, "docDensity" float NOT NULL, "docTemperature" float NOT NULL, "counterBefore" float DEFAULT (0), "counterAfter" float DEFAULT (0), "volumeBefore" float DEFAULT (0), "volumeAfter" float DEFAULT (0), "levelBefore" float DEFAULT (0), "levelAfter" float DEFAULT (0), "dispenserError" boolean DEFAULT (0), "dispenserId" integer, "driverId" integer, "fuelId" integer, "fuelHolderId" integer, "refineryId" integer, "trailerId" integer, "vehicleId" integer, "tankId" integer, "shiftId" integer, "dateTTN" integer NOT NULL DEFAULT (strftime('%s', 'now')), "comment" text, "sourceTankId" integer, "carrierId" integer, "dockId" integer, CONSTRAINT "FK_1a946e8faa240020b1519cbd7ef" FOREIGN KEY ("sourceTankId") REFERENCES "tank" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0fe8d164f8e00199fff3a1ab00e" FOREIGN KEY ("shiftId") REFERENCES "shift" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7c627c969c9eeccceb4b290806c" FOREIGN KEY ("tankId") REFERENCES "tank" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_289c58cdde3f9e5e7d1c9111b6f" FOREIGN KEY ("vehicleId") REFERENCES "vehicle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_92a920d504d3057fbca9e0acb81" FOREIGN KEY ("trailerId") REFERENCES "trailer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4fa6456e8465dc3738f18ade562" FOREIGN KEY ("refineryId") REFERENCES "refinery" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2a95009217197ba57060423fc00" FOREIGN KEY ("fuelHolderId") REFERENCES "fuel_holder" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_1ec7313173df4fe9b3d0cd9ff56" FOREIGN KEY ("fuelId") REFERENCES "fuel" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4fe00161ef48138bfa3f434d1e2" FOREIGN KEY ("driverId") REFERENCES "driver" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_44a506978936572278194b22c22" FOREIGN KEY ("dispenserId") REFERENCES "dispenser" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
    );
    await queryRunner.query(
      `INSERT INTO "temporary_operation"("id", "createdAt", "updatedAt", "deletedAt", "type", "status", "vehicleState", "destination", "numberTTN", "startedAt", "finishedAt", "docVolume", "factVolume", "factWeight", "docWeight", "docDensity", "docTemperature", "counterBefore", "counterAfter", "volumeBefore", "volumeAfter", "levelBefore", "levelAfter", "dispenserError", "dispenserId", "driverId", "fuelId", "fuelHolderId", "refineryId", "trailerId", "vehicleId", "tankId", "shiftId", "dateTTN", "comment", "sourceTankId", "carrierId", "dockId") SELECT "id", "createdAt", "updatedAt", "deletedAt", "type", "status", "vehicleState", "destination", "numberTTN", "startedAt", "finishedAt", "docVolume", "factVolume", "factWeight", "docWeight", "docDensity", "docTemperature", "counterBefore", "counterAfter", "volumeBefore", "volumeAfter", "levelBefore", "levelAfter", "dispenserError", "dispenserId", "driverId", "fuelId", "fuelHolderId", "refineryId", "trailerId", "vehicleId", "tankId", "shiftId", "dateTTN", "comment", "sourceTankId", "carrierId", "dockId" FROM "operation"`,
    );
    await queryRunner.query(`DROP TABLE "operation"`);
    await queryRunner.query(
      `ALTER TABLE "temporary_operation" RENAME TO "operation"`,
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "operation" RENAME TO "temporary_operation"`,
    );
    await queryRunner.query(
      `CREATE TABLE "operation" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "updatedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "deletedAt" datetime, "type" varchar CHECK( "type" IN ('outcome','supply','internal','mixed','return') ) NOT NULL, "status" varchar CHECK( "status" IN ('created','started','progress','interrupted','stopped','finished') ) NOT NULL DEFAULT ('created'), "vehicleState" text, "destination" text, "numberTTN" text, "startedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "finishedAt" integer NOT NULL DEFAULT (strftime('%s', 'now')), "docVolume" float NOT NULL, "factVolume" float, "factWeight" float, "docWeight" float NOT NULL, "docDensity" float NOT NULL, "docTemperature" float NOT NULL, "counterBefore" float DEFAULT (0), "counterAfter" float DEFAULT (0), "volumeBefore" float DEFAULT (0), "volumeAfter" float DEFAULT (0), "levelBefore" float DEFAULT (0), "levelAfter" float DEFAULT (0), "dispenserError" boolean DEFAULT (0), "dispenserId" integer, "driverId" integer, "fuelId" integer, "fuelHolderId" integer, "refineryId" integer, "trailerId" integer, "vehicleId" integer, "tankId" integer, "shiftId" integer, "dateTTN" integer NOT NULL DEFAULT (strftime('%s', 'now')), "comment" text, "sourceTankId" integer, CONSTRAINT "FK_1a946e8faa240020b1519cbd7ef" FOREIGN KEY ("sourceTankId") REFERENCES "tank" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0fe8d164f8e00199fff3a1ab00e" FOREIGN KEY ("shiftId") REFERENCES "shift" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7c627c969c9eeccceb4b290806c" FOREIGN KEY ("tankId") REFERENCES "tank" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_289c58cdde3f9e5e7d1c9111b6f" FOREIGN KEY ("vehicleId") REFERENCES "vehicle" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_92a920d504d3057fbca9e0acb81" FOREIGN KEY ("trailerId") REFERENCES "trailer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4fa6456e8465dc3738f18ade562" FOREIGN KEY ("refineryId") REFERENCES "refinery" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2a95009217197ba57060423fc00" FOREIGN KEY ("fuelHolderId") REFERENCES "fuel_holder" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_1ec7313173df4fe9b3d0cd9ff56" FOREIGN KEY ("fuelId") REFERENCES "fuel" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4fe00161ef48138bfa3f434d1e2" FOREIGN KEY ("driverId") REFERENCES "driver" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_44a506978936572278194b22c22" FOREIGN KEY ("dispenserId") REFERENCES "dispenser" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
    );
    await queryRunner.query(
      `INSERT INTO "operation"("id", "createdAt", "updatedAt", "deletedAt", "type", "status", "vehicleState", "destination", "numberTTN", "startedAt", "finishedAt", "docVolume", "factVolume", "factWeight", "docWeight", "docDensity", "docTemperature", "counterBefore", "counterAfter", "volumeBefore", "volumeAfter", "levelBefore", "levelAfter", "dispenserError", "dispenserId", "driverId", "fuelId", "fuelHolderId", "refineryId", "trailerId", "vehicleId", "tankId", "shiftId", "dateTTN", "comment", "sourceTankId") SELECT "id", "createdAt", "updatedAt", "deletedAt", "type", "status", "vehicleState", "destination", "numberTTN", "startedAt", "finishedAt", "docVolume", "factVolume", "factWeight", "docWeight", "docDensity", "docTemperature", "counterBefore", "counterAfter", "volumeBefore", "volumeAfter", "levelBefore", "levelAfter", "dispenserError", "dispenserId", "driverId", "fuelId", "fuelHolderId", "refineryId", "trailerId", "vehicleId", "tankId", "shiftId", "dateTTN", "comment", "sourceTankId" FROM "temporary_operation"`,
    );
    await queryRunner.query(`DROP TABLE "temporary_operation"`);
    await queryRunner.query(`DROP TABLE "dock"`);
    await queryRunner.query(`DROP TABLE "carrier"`);
  }
}
